[theme]
base = "dark"
primaryColor             = "#10B981"
backgroundColor          = "#0B1120"
secondaryBackgroundColor = "#101A2C"
textColor                = "#D8E4F0"
font                     = "sans serif"

[server]
headless = true
